# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasks.proto',
  package='tasks',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btasks.proto\x12\x05tasks\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\tIDRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"y\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12!\n\x08priority\x18\x04 \x01(\x0e\x32\x0f.tasks.Priority\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x06 \x01(\t*)\n\x08Priority\x12\x07\n\x03Low\x10\x00\x12\n\n\x06Medium\x10\x01\x12\x08\n\x04High\x10\x02\x32\xf4\x01\n\x0bTaskService\x12$\n\x06\x43reate\x12\x0b.tasks.Task\x1a\x0b.tasks.Task\"\x00\x12\'\n\x04Read\x12\x10.tasks.IDRequest\x1a\x0b.tasks.Task\"\x00\x12/\n\x06Update\x12\x0b.tasks.Task\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\x06\x44\x65lete\x12\x10.tasks.IDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12/\n\x04List\x12\x16.google.protobuf.Empty\x1a\x0b.tasks.Task\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_PRIORITY = _descriptor.EnumDescriptor(
  name='Priority',
  full_name='tasks.Priority',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Low', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Medium', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='High', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=199,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_PRIORITY)

Priority = enum_type_wrapper.EnumTypeWrapper(_PRIORITY)
Low = 0
Medium = 1
High = 2



_IDREQUEST = _descriptor.Descriptor(
  name='IDRequest',
  full_name='tasks.IDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tasks.IDRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=74,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='tasks.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tasks.Task.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tasks.Task.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='tasks.Task.category', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='tasks.Task.priority', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='tasks.Task.content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='due_date', full_name='tasks.Task.due_date', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=197,
)

_TASK.fields_by_name['priority'].enum_type = _PRIORITY
DESCRIPTOR.message_types_by_name['IDRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.enum_types_by_name['Priority'] = _PRIORITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDRequest = _reflection.GeneratedProtocolMessageType('IDRequest', (_message.Message,), dict(
  DESCRIPTOR = _IDREQUEST,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:tasks.IDRequest)
  ))
_sym_db.RegisterMessage(IDRequest)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:tasks.Task)
  ))
_sym_db.RegisterMessage(Task)



_TASKSERVICE = _descriptor.ServiceDescriptor(
  name='TaskService',
  full_name='tasks.TaskService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=243,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='tasks.TaskService.Create',
    index=0,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='tasks.TaskService.Read',
    index=1,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=_TASK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='tasks.TaskService.Update',
    index=2,
    containing_service=None,
    input_type=_TASK,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='tasks.TaskService.Delete',
    index=3,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='tasks.TaskService.List',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TASK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKSERVICE)

DESCRIPTOR.services_by_name['TaskService'] = _TASKSERVICE

# @@protoc_insertion_point(module_scope)
